import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import RootLayoutWrapper from '@/components/wrapper/RootLayoutWrapper';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Slack Clone',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<meta name='apple-mobile-web-app-title' content='Slack Clone' />
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<RootLayoutWrapper>{children}</RootLayoutWrapper>
			</body>
		</html>
	);
}
